// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNeKBFSaCtsxrFq7w9K60i5UojQrOf24',
    appId: '1:996238923613:web:429237b3e5f2637069fab4',
    messagingSenderId: '996238923613',
    projectId: 'pex-2026',
    authDomain: 'pex-2026.firebaseapp.com',
    storageBucket: 'pex-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwJv4uCDH2Htlor8YgwxJ0xsUZHAIA84',
    appId: '1:996238923613:android:fa52cc7424f5d2b369fab4',
    messagingSenderId: '996238923613',
    projectId: 'pex-2026',
    storageBucket: 'pex-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsL-TpKoIY7QFAwnFHLVkIGoN9F53cPGI',
    appId: '1:996238923613:ios:14f8f1a2ea9f70a669fab4',
    messagingSenderId: '996238923613',
    projectId: 'pex-2026',
    storageBucket: 'pex-2026.firebasestorage.app',
    iosBundleId: 'com.pex2026.pex2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsL-TpKoIY7QFAwnFHLVkIGoN9F53cPGI',
    appId: '1:996238923613:ios:14f8f1a2ea9f70a669fab4',
    messagingSenderId: '996238923613',
    projectId: 'pex-2026',
    storageBucket: 'pex-2026.firebasestorage.app',
    iosBundleId: 'com.pex2026.pex2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaNeKBFSaCtsxrFq7w9K60i5UojQrOf24',
    appId: '1:996238923613:web:0bf8cc714235ca4c69fab4',
    messagingSenderId: '996238923613',
    projectId: 'pex-2026',
    authDomain: 'pex-2026.firebaseapp.com',
    storageBucket: 'pex-2026.firebasestorage.app',
  );

}